### ISSUE TITLE
AttributeError: module 'custom_components.hysenheating.climate' has no attribute 'setup_platform'

### ISSUE THREAD

**Issue by alattincakici** [uspass/hysenheating#1]
Thank you very much for your work.
I get this error after the integration of the component when hassio 0.88.2 restarts:

019-03-10 21:52:03 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform hysenheating
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'custom_components.hysenheating.climate' has no attribute 'setup_platform'
2019-03-10 21:52:03 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform hysenheating
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 124, in _async_setup_platform
    task = async_create_setup_task()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 89, in async_create_setup_task
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'custom_components.hysenheating.climate' has no attribute 'setup_platform'

**Comment by alattincakici** [comment]
And I think you need an additional folder config/custom_components/hysenheating/**climate**/

**Comment by alattincakici** [comment]
Updated to 0.89.1 and deleted climate folder now works. So my mistake was sorry. You can now close this issue
